[build-system]
requires = [
    "setuptools>=70.1.0",
    "wheel>=0.38.0",
    "Cython>=3.0.4",
    "numpy>=2.0.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "cashflower"
version = "0.10.8"
description = "Framework for actuarial cash flow models"
readme = "README.md"
requires-python = ">=3.11"
authors = [{name = "Zuzanna Chmielewska"}]
dependencies = [
    "pandas==2.2.2",
    "psutil==5.9.5",
    "networkx==3.1",
    "numpy==2.0.1",
]

[project.urls]
Source = "https://github.com/acturtle/cashflower"
Tracker = "https://github.com/acturtle/cashflower/issues"
Documentation = "https://cashflower.acturtle.com"
"Cheat sheet" = "https://www.acturtle.com/static/pdf/cheat_sheet.pdf"

[project.optional-dependencies]
dev = [
    "pytest==7.4.2",
    "ruff==0.0.291",
    "Sphinx==7.2.6",
    "furo==2023.9.10",
]

[tool.setuptools]
include-package-data = true

[tool.cibuildwheel]
skip = "pp* *_i686"

[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
line-length = 160
exclude = [
    "cashflower/__init__.py",
    "cashflower/model_tpl/model.py",
]
